travis:
  secure:
    BINSTAR_TOKEN: hDgb5u+wWJ3kaxAzftGHCLbwSN4K4+rjhXR20ruYrrzsjijxwYtYCG45x/w9ujAWkWAd5Ovi0u0xYAcTfjYMTZomEY+4ttQQUQVRTtITb8a18ONkugkSvWoQCmnJzHDZc8SKbyA40gl2D2VVUU/atDdA9l9mgx8pDTCDATRcxJycYvAN8RRRigrlT18KwpeAymkGACm1C6fSYJnbwT4xuCNeD4seNg/LhNiwh3RnYpYf1tsOfMqkqh1usKKi1ZlotXSIUnbxtls0M+ecIl5n8MiGYvo5QVuEa+CBHaiBjwf+VdDz1b8vFcVnnJ8xCY23quIBIlRcGSQItLEcZOkfb5nLv1jwc9hx/tPQWM4M1ULjRR9jTP/8HA3lM/kQdcxS1PDgQXZ82W3yvBbDQctGiK4gu/PHWF8WvEP/1K+XKBK22gid3jLThhLixeEDxAwBxBLBVv368sV7BEtDCBJzt0plH9AF+jMw7WvwqjaMk51A0N3A/sl7DLIR/I8ES6VW4S8MlbT8m34ykIo1/xvNQsGUxb4ThnZz2CXRHJOGmWh1IhSQlYOmJhbsY0CmfWo/r4TENryB2E3VPNj9qyckeSMxQRRwMfSHgPazRCEnU7rkur/ySEZ8IsNnnxfyS9CjMyba9Z/uKbCNuK+kH/lF3Tb0XPayup2Z0GAP0O6VFY4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
